# Generated by Django 5.1.1 on 2024-12-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo_camara', models.CharField(max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resolucion_mp', models.CharField(max_length=300)),
                ('fecha_agregada', models.DateField()),
            ],
        ),
    ]
