# Generated by Django 5.1.1 on 2024-12-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_empleado', models.PositiveIntegerField()),
                ('id_producto', models.PositiveIntegerField()),
                ('id_cliente', models.PositiveIntegerField()),
                ('fecha_venta', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
